package com.cellularautomata.image;

import com.cellularautomata.config.WorkspaceConfig;
import com.cellularautomata.engine.Vector;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.imageio.ImageIO;

/**
 * The <code>AutomatonImage</code> class generates images of an automaton. This class originally
 * creates small images of automatons. When required, it resizes the small images into larger ones.
 * Since the images are entirely composed of black and white pixels, increasing the size of the
 * original images does not ruin the image quality.
 *
 * @author Rainer Pons
 */
public final class AutomatonImage {

  private AutomatonImage() {
    throw new IllegalStateException("Utility class");
  }

  /**
   * Generates a (small) buffered image of an automaton.
   *
   * @param map associative array of generation count and neighborhood vectors
   * @param states the number of states (determines grayscale shading)
   * @return image generated by map
   */
  public static BufferedImage getImageFromMap(Map<Integer, Vector> map, int states) {
    final int size = map.get(0).getSize();
    var image = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);

    // For states > 2, evenly spaced grayscale from black (0) to white (255)
    // S=0 -> 255 (white), S=states-1 -> 0 (black). Wait, usually higher states are darker.
    // The issue says:
    // 2 states: black, white. (Assume 0=white, 1=black? Original: '1' is black(0), '0' is
    // white(16777215))
    // Let's preserve original mapping: 0 -> white(255), max_state -> black(0).
    // Issue examples:
    // 3 states -> black, gray, white
    // 5 states -> black, 75% gray, 50% gray, 25% gray, white
    // This implies 0 = white, max = black, or vice versa?
    // "5 states -> black, 75% gray, 50% gray, 25% gray, white"
    // Usually state 0 is white (empty), highest state is black.
    for (var entry : map.entrySet()) {
      var stateString = entry.getValue().getState();
      for (int i = 0; i < stateString.length(); i++) {
        int j = entry.getKey();
        int stateValue = stateString.charAt(i) - '0';

        // grayscale value from 0 (black) to 255 (white).
        // 0 -> 255
        // states-1 -> 0
        int gray = 255 - (stateValue * 255 / (states - 1));
        int rgb = (gray << 16) | (gray << 8) | gray;
        image.setRGB(i, j, rgb);
      }
    }
    return image;
  }

  /**
   * Generates a resized version of a buffered image created by the method {@link
   * #getImageFromMap(Map)}.
   *
   * @param width desired width of new image
   * @param height desired height of new image
   * @param image image to be resized
   * @return new image with the desired width and height
   */
  public static BufferedImage resizeImage(int width, int height, BufferedImage image) {
    var resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
    var graphic = resizedImage.createGraphics();
    graphic.drawImage(image, 0, 0, width, height, null);
    graphic.dispose();
    return resizedImage;
  }

  /**
   * Creates the name of a file given a workspace configuration, rule number, lattice size, and
   * states.
   *
   * @param config the workspace configuration
   * @param rule local update rule number
   * @param size lattice size
   * @param states number of states
   * @return a filename following the convention:
   *     workspace_[states{states}_]rule{rule}_size{size}_{timestamp}.png
   */
  public static String getFileName(WorkspaceConfig config, int rule, int size, int states) {
    String timestamp =
        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH-mm-ss"));
    if (config == WorkspaceConfig.TOTALISTIC) {
      return config.name().toLowerCase()
          + "_states"
          + states
          + "_rule"
          + rule
          + "_size"
          + size
          + "_"
          + timestamp
          + ".png";
    }
    return config.name().toLowerCase() + "_rule" + rule + "_size" + size + "_" + timestamp + ".png";
  }

  /**
   * Saves the provided image to the specified file.
   *
   * @param image the image to save
   * @param file the destination file
   * @throws IOException if an error occurs during writing
   */
  public static void saveImage(BufferedImage image, File file) throws IOException {
    if (!file.createNewFile()) {
      System.err.println("Warning: file already exists, overwriting: " + file.getPath());
    }
    ImageIO.write(image, "PNG", file);
  }
}
