package com.cellularautomata.image;

import com.cellularautomata.engine.Vector;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.imageio.ImageIO;

/**
 * The <code>AutomatonImage</code> class generates images of an automaton. This class originally
 * creates small images of automatons. When required, it resizes the small images into larger ones.
 * Since the images are entirely composed of black and white pixels, increasing the size of the
 * original images does not ruin the image quality.
 *
 * @author Rainer Pons
 */
public final class AutomatonImage {

  private AutomatonImage() {
    throw new IllegalStateException("Utility class");
  }

  /**
   * Generates a (small) buffered image of an automaton.
   *
   * @param map associative array of generation count and neighborhood vectors
   * @param states the number of states (determines grayscale shading)
   * @return image generated by map
   */
  public static BufferedImage getImageFromMap(Map<Integer, Vector> map, int states) {
    final int size = map.get(0).getSize();
    var image = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);

    // For states > 2, the image is rendered with an evenly spaced grayscale palette.
    // The state '0' maps to white (RGB 255) and the highest state 'states - 1' maps to black (RGB
    // 0).
    for (var entry : map.entrySet()) {
      var stateString = entry.getValue().getState();
      for (int i = 0; i < stateString.length(); i++) {
        int j = entry.getKey();
        int stateValue = stateString.charAt(i) - '0';

        // grayscale value from 0 (black) to 255 (white).
        // 0 -> 255
        // states-1 -> 0
        int gray = 255 - (stateValue * 255 / (states - 1));
        int rgb = (gray << 16) | (gray << 8) | gray;
        image.setRGB(i, j, rgb);
      }
    }
    return image;
  }

  /**
   * Generates a resized version of a buffered image created by the method {@link
   * #getImageFromMap(Map)}.
   *
   * @param width desired width of new image
   * @param height desired height of new image
   * @param image image to be resized
   * @return new image with the desired width and height
   */
  public static BufferedImage resizeImage(int width, int height, BufferedImage image) {
    var resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
    var graphic = resizedImage.createGraphics();
    graphic.drawImage(image, 0, 0, width, height, null);
    graphic.dispose();
    return resizedImage;
  }

  /**
   * Saves the provided image to the specified file.
   *
   * @param image the image to save
   * @param file the destination file
   * @throws IOException if an error occurs during writing
   */
  public static void saveImage(BufferedImage image, File file) throws IOException {
    if (!file.createNewFile()) {
      System.err.println("Warning: file already exists, overwriting: " + file.getPath());
    }
    ImageIO.write(image, "PNG", file);
  }
}
